import { SurveySubmission } from "./types";

export const INITIAL_PRODUCTS = [
  "Tour Histórico e Cultural",
  "Tour Pedagógico Industrial",
  "Tour de Inovação & Tecnologia",
  "Tour de Integração Corporativa",
  "Tour Institucional"
];

export const INITIAL_LEADERS = [
  "Amanda Costa",
  "Carlos Menezes",
  "Fabiana Rosa",
  "Roberto Santos",
  "Sofia Albuquerque"
];

export const INITIAL_SUBMISSIONS: SurveySubmission[] = [
  {
    id: "sub-1",
    date: "2026-05-10",
    nomeCompleto: "Felipe Andrade Silva",
    idade: 22,
    liderEducador: "Amanda Costa",
    produto: "Tour Histórico e Cultural",
    participantes: 25,
    assistente: "VINICIUS",
    unidade: "PRN",
    notaClareza: 9,
    justificativaClareza: "As explicações sobre a história do prédio foram muito enriquecedoras.",
    notaAcolhimento: 10,
    justificativaAcolhimento: "Fomos recebidos com muito carinho e sorriso no rosto logo na chegada.",
    notaAssistente: 10,
    justificativaAssistente: "Vinicius é super carismático, guiou o grupo com excelência e demonstrou domínio.",
    melhorias: "Gostaria de sugerir mais tempo livre ao final para fotos."
  },
  {
    id: "sub-2",
    date: "2026-05-12",
    nomeCompleto: "Beatriz Oliveira Souza",
    idade: 29,
    liderEducador: "Carlos Menezes",
    produto: "Tour Pedagógico Industrial",
    participantes: 35,
    assistente: "VINICIUS",
    unidade: "PRN",
    notaClareza: 8,
    justificativaClareza: "Informações bem técnicas, porém passadas de maneira muito didática para os nossos alunos.",
    notaAcolhimento: 9,
    justificativaAcolhimento: "Recepção atenciosa, organizaram o grupo de forma rápida.",
    notaAssistente: 9,
    justificativaAssistente: "Muito calmo e atencioso nas respostas às perguntas dos estudantes.",
    melhorias: "A acústica em alguns setores da fábrica dificulta ouvir quem está longe."
  },
  {
    id: "sub-3",
    date: "2026-05-14",
    nomeCompleto: "Gustavo Santos Pereira",
    idade: 43,
    liderEducador: "Fabiana Rosa",
    produto: "Tour de Inovação & Tecnologia",
    participantes: 18,
    assistente: "VINICIUS",
    unidade: "PRN",
    notaClareza: 10,
    justificativaClareza: "Absolutamente clareza total sobre os processos tecnológicos do núcleo de controle.",
    notaAcolhimento: 10,
    justificativaAcolhimento: "O time de Boas-Vindas nos ofereceu água, café e suporte excepcional para os notebooks.",
    notaAssistente: 10,
    justificativaAssistente: "Excelente profissionalismo, muito seguro ao conduzir o passeio técnico.",
    melhorias: "Nada, tudo estava perfeito!"
  },
  {
    id: "sub-4",
    date: "2026-05-15",
    nomeCompleto: "Mariana Alencar Guedes",
    idade: 31,
    liderEducador: "Roberto Santos",
    produto: "Tour de Integração Corporativa",
    participantes: 42,
    assistente: "VINICIUS",
    unidade: "PRN",
    notaClareza: 9,
    justificativaClareza: "Muito prático, facilitou bastante a compreensão da cultura da organização.",
    notaAcolhimento: 8,
    justificativaAcolhimento: "Excelente organização do auditório, fomos muito bem acolhidos.",
    notaAssistente: 10,
    justificativaAssistente: "Vinicius é fora da curva, consegue reter a atenção de um grupo grande com facilidade.",
    melhorias: "Talvez entregar um guia em panfleto ou digital para posterior consulta."
  },
  {
    id: "sub-5",
    date: "2026-05-16",
    nomeCompleto: "Ricardo Mendes Lima",
    idade: 55,
    liderEducador: "Sofia Albuquerque",
    produto: "Tour Institucional",
    participantes: 15,
    assistente: "VINICIUS",
    unidade: "PRN",
    notaClareza: 10,
    justificativaClareza: "Visão sistêmica fantástica sobre a governança e valores apresentados.",
    notaAcolhimento: 10,
    justificativaAcolhimento: "Simpatia contagiante do portal até à sala de conferência.",
    notaAssistente: 10,
    justificativaAssistente: "Super paciente com o pessoal de mais idade da nossa diretoria.",
    melhorias: "Considero útil sinalizar melhor as vagas de estacionamento para o tour."
  },
  {
    id: "sub-6",
    date: "2026-05-18",
    nomeCompleto: "Patricia Xavier Torres",
    idade: 25,
    liderEducador: "Amanda Costa",
    produto: "Tour Histórico e Cultural",
    participantes: 30,
    assistente: "VINICIUS",
    unidade: "PRN",
    notaClareza: 9,
    justificativaClareza: "Detalhamento maravilhoso dos acervos históricos.",
    notaAcolhimento: 10,
    justificativaAcolhimento: "O time é espetacular na recepção e identificação dos participantes.",
    notaAssistente: 10,
    justificativaAssistente: "Vinicius deu um show de conhecimento e carisma no tour.",
    melhorias: "Nenhuma sugestão, nota dez para o evento."
  },
  {
    id: "sub-7",
    date: "2026-05-19",
    nomeCompleto: "Carlos Roberto Neves",
    idade: 37,
    liderEducador: "Fabiana Rosa",
    produto: "Tour de Inovação & Tecnologia",
    participantes: 20,
    assistente: "VINICIUS",
    unidade: "PRN",
    notaClareza: 8,
    justificativaClareza: "Boas analogias para explicar conceitos complicados de software.",
    notaAcolhimento: 9,
    justificativaAcolhimento: "Ambiente muito caloroso e atencioso.",
    notaAssistente: 9,
    justificativaAssistente: "Muito gentil e respondeu todas as dúvidas pacienciosamente.",
    melhorias: "As demonstrações práticas poderiam durar alguns minutos a mais."
  },
  {
    id: "sub-8",
    date: "2026-05-20",
    nomeCompleto: "Camila Rodrigues Pinheiro",
    idade: 19,
    liderEducador: "Carlos Menezes",
    produto: "Tour Pedagógico Industrial",
    participantes: 50,
    assistente: "VINICIUS",
    unidade: "PRN",
    notaClareza: 7,
    justificativaClareza: "Bons slides de apoio, mas correu um pouco por conta do tempo do ônibus.",
    notaAcolhimento: 8,
    justificativaAcolhimento: "A equipe de boas-vindas foi prestativa nos crachás de acesso secundários.",
    notaAssistente: 8,
    justificativaAssistente: "Conduziu muito bem mesmo em um grupo agitado de estudantes.",
    melhorias: "Prever tempo extra para lanche ou área de descanso intermediária."
  },
  {
    id: "sub-9",
    date: "2026-05-21",
    nomeCompleto: "André Luis Martins",
    idade: 48,
    liderEducador: "Sofia Albuquerque",
    produto: "Tour Institucional",
    participantes: 12,
    assistente: "VINICIUS",
    unidade: "PRN",
    notaClareza: 10,
    justificativaClareza: "Fácil de compreender todas as metas de ESG apresentadas pelo condutor.",
    notaAcolhimento: 10,
    justificativaAcolhimento: "Impecável o lanche de boas-vindas e a sinalização dos halls.",
    notaAssistente: 10,
    justificativaAssistente: "Domínio completo de oratória e simpatia ímpar do Vinicius.",
    melhorias: "A sala estava um pouco fria demais devido ao ar condicionado potente."
  },
  {
    id: "sub-10",
    date: "2026-05-21",
    nomeCompleto: "Juliana Mendes Garcia",
    idade: 27,
    liderEducador: "Roberto Santos",
    produto: "Tour de Integração Corporativa",
    participantes: 28,
    assistente: "VINICIUS",
    unidade: "PRN",
    notaClareza: 9,
    justificativaClareza: "Conteúdo focado nos reais desafios profissionais dos novos colaboradores.",
    notaAcolhimento: 10,
    justificativaAcolhimento: "Recepção maravilhosa com as boas-vindas impressas no mural digital.",
    notaAssistente: 10,
    justificativaAssistente: "Comunicação assertiva e alegre, um excelente exemplo de anfitrião.",
    melhorias: "Fornecer caneta extra e bloco de notas físico para todos."
  }
];
